######################GrowthCurve.plot#######################
#######################################################################
#png("TL growth curve(p variable; µ1=0 µ2=N(1;0,5)50000it.png")
plot(rep(mu.X,3),Cal.sim$mean$y1,ylim=c(0,max(Cal.sim$mean$y2)*1.2),xlim=c(Cal.sim$mean$X0*1.2, max(mu.X)*1.2),xlab="Dose (sec. beta)",ylab="Intensity (a.u)")
a<-rvnorm(1,Cal.sim$mean$nbeta,Cal.sim$sd$nbeta)
b<-rvnorm(1,Cal.sim$mean$mbeta,Cal.sim$sd$mbeta)
xn<-rvnorm(1,Cal.sim$mean$X0,Cal.sim$sd$X0)
rvpar(line.sample=20)
abline.rv(a,b,col=5)
points.rv(mu.X, a+b*mu.X)
points(rep(mu.X,3),Cal.sim$mean$y1,col=2)
points.rv(xn, 0,col=4)
points(mx,my)
abline(mu.nB0,mu.mB0)	
#dev.off()

#png("bornes plateau.png")
t1<-rvnorm(1,Cal.sim$mean$Temp1,Cal.sim$sd$Temp1)
g1<-hist(sims(t1)[sims(t1)>200&sims(t1)<650],breaks=seq(200,650,5))
t2<-rvnorm(1,Cal.sim$mean$Temp2,Cal.sim$sd$Temp2)
g2<-hist(sims(t2)[sims(t2)>200&sims(t2)<650],breaks=seq(200,650,5))
plot(g1,xlim=c(200,600),xlab="Temperature (°C)")
lines(g2, col=3)
#dev.off()
